### ISSUE TITLE
Alternative to nodemcu-uploader?

### ISSUE THREAD

**Issue by Spiritdude** [Godzil/nodemcu-webide#2]
`nodemcu-uploader` seems only partially work for me (Wemos D1 Mini): it runs once `make upload_all` (previously installed original nodemcu-webide installed via `.bin` file and `esptool.py`), and overwrites / updates webide, and then doesn't start anymore (no wifi AP).

Is there a way to use `esptool.py` and flash a `.bin` file to be sure?

I like to extend your webide and test how far you updated the original repo.

**Comment by Godzil** [comment]
You make an interesting point.

First, I do have no plan at all to distributes ready to flash .bin file for multiples reason:
- The build file may not fit your need of modules, I may want to have ws2812, but you may not need it and want the u8c library.
- NodeMCU tend to move fast and the version you build today will be obsolete tomorrow, I really can't keep on that. For example the version provided on the original repo is really old and does have lots of bugs that been fixed since.

The (a bit too complexe) makefile I made suppose that you are using a quite fresh version of nodemcu lua, it there are timers or tools running that print thing on the Lua console it can get confused and that's probably why it failed on your side. There are probably room for improvement on that tool, but it works reasonably well.

So the process to install my fork of nodemcu-webide is to first make a fresh version of NodeMCU Lua. I do use https://nodemcu-build.com for building a version that fit my needs, then I flash my ESP8266 with that version using esptool.py, then I upload the file using nodemcu-uploader.

The makefile I have here is used to fetch the last known working version of nodemcu-httpserver and nodemcu-uploader, then patch httpserver as needed (a small change needed to add support for webide, and trying to make most of theses changed upstream) then it allow to upload httpserver and webide to the ESP8266.

There is potentially a way of making a SPIFFS only bin file using a tool like https://github.com/igrr/mkspiffs but I never used it and it may not be as easy as it is currently, but that something that could be used for release, but for sure I will not for now build version that include the lua firmware as it will never fit everyone needs for either modules or versions.

**Comment by Spiritdude** [comment]
Understood.

I also tried to get a custom Nodemcu Lua, flashed it etc, once all files are uploaded via `make` 
& `nodemcu-uploader`, is there anything else needed to make it start the Access Point?

**Comment by HHHartmann** [comment]
Just to make sure:
You did adapt the httpserver-conf.lua file to suit your needs. The default configuration is conf.wifi.mode = wifi.STATION

**Comment by Spiritdude** [comment]
I really struggled to get proper nodemcu firmware, flash, upload (`make upload_all`), and get the AP working (1-2 hours); it seems the entire setup is quite fragile. Finally AP is up and http://192.168.111.1 shows the WebIDE. 

I see files on the left-hand side:
```
 http/hello-world.lua
 http/led-matrix.lua
 http/led-stick.lua
 http/led-text.lua
 http/robot.lua
 http/system-info.lua
 http/ws-echo.lua
 http/ws-led.lua
 http/ws-robot.lua
 init.lua
 startup.lua
```

![screenshot from 2017-12-30 18-58-05](https://user-images.githubusercontent.com/2078766/34456303-7c9f88c8-ed93-11e7-8870-37d38f7378d4.png)

like `http/system-info.lua` and preview leads to `404 Not Found`, altering `http://192.168.111.1/http/system-info.lua` in the browser to `http://192.168.111.1/system-info.lua` gives system information.

What am I missing?

I create a new file 'new1.lua' via WebIDE, but it can't access it ('preview' it) either, I have to move into `http/new1.lua` but access it via `http://192.168.111.1/new1.lua` manually again.

Is there more configuration I have to edit?

Are the files I listed above the default view?

**Comment by HHHartmann** [comment]
The problem here is that the nodemcu-httpserver servs files from the http "Directory" as its root.
So a file "http/hello" is served as "http://myHost/hello". Lua files are then also executed and not just served as is.
So for a view functionality the file-api.lua interface would have to be used in index.js.

**Comment by Spiritdude** [comment]
@HHHartmann so it's broken . . . the WebIDE.

@Godzil you forked the original NodeMCU WebIDE, restructured the code base, and changed defaults (no AP by default, etc) . . .  I assume at one point it worked, why did it break all of the sudden? I guess part (httpserver) you rely on changed behaviour?

I'm new to ESP8266 coding, I really like the REST approach to edit/compile/execute LUA files. I have some ideas to channel LUA output back to console/restful and improve the web GUI overall - I like to have this as my base framework (I tested ESP8266 Arduino, Espruino for ESP8266) but I prefer LUA (even it's relatively new for me) due the low memory footprint.

So, what shall I do now? Adapt the original NodeMCU WebIDE and ignore all work of @Godzil did, or wait so this package is back working properly again as expected (compared to the original)? I don't understand the code-base sufficiently yet to fix it:

* what files are supposed to be edited(able)? only in `http/` or also one level higher? if so, all files listed and therefore editable should be (pre)viewable then, that would be consistent logic.
* what does 'preview' actually mean here? the .lua file is compiled and executed in the context of httpserver.
* what about non-lua files? editable as well?

## Recommendation
- make wifi.SOFTAP the default, change default password not be the SSID, but `Pass<ID>` as it was before.
- document basic functionality: what does the IDE actually do (lua vs non-lua files)? what's good practice to code with WebIDE and make it work beyond reboots.
- ensure basic functionality working, the examples seem gone (unlisted), e.g. `http/ws-echo.lua` is listed, but `http/ws-echo.html` is not.
- introduce version numbering (itself and all parts)
- keep track of components (not sure what's the best way, to have components improve yet to ensure they work properly = testing and documenting versions used)
- provide `.bin` to start with for newbies, something to work out of the box (I'm willing to provide that)

Here a quick hack to make `http/*.lua` files working again, in `index.js` I added `url = url.replace('http/','')` in `preview()`, and make a xhr() to fetch response and put into new #output DIV: more compact and readable `system-info2.lua`:

![screenshot from 2017-12-31 14-23-17-blurred](https://user-images.githubusercontent.com/2078766/34461900-c68be590-ee37-11e7-847a-37281eecca61.png)

**Comment by Spiritdude** [comment]
Main ideas of mine:
* stdout/stderr output (via xhr())
  * output time elapsed (e.g. "hello world" (5ms))
  * distinction of stdout vs stderr (e.g. compiling errors), keep in a scrollable DIV
* new tab for html files which require that, with `window.open()` as before (like to test if ws-echo.* example works within a DIV or really needs its down tab)
* AP vs WLAN client built-in to config (no need to leave WebIDE), edit/save some `wlan.lua` config file or so, with fallback behaviour: if WLAN client join fails, starting AP etc (ensure ESP8266 node is somehow reachable)

**Comment by Godzil** [comment]
Thanks @HHHartmann to answer to the previous questions

@Spiritdude some quick answers:
(don't have a lot of time to work on webide at the moment, will probably have more time after the holidays)
I forked the original WebIDE because the lua interpreter and httpserver it was using is old and really buggy and was not filling my needs (I use recent version of nodemcu lua and need recent version, especially as I custom build them)

Unless you updated the submodules on your local clone, git use a specific version of the tools I use (uploader and httpserver) so no risk of things to break without warning, so the httpserver you have is the one I expect, unless you updated the modules.

The version actually on the repository has been tested on a Wemos D1 Pro and another board I do have, but as basically all ESP8266 board are equivalent, that does not have a real impact here.

Don't forget that this repository even if partly working is still a work in progress, I want to update part of the IDE itself because it have some bugs that was fixed on the official version, and the current interface is a bit difficult to use, but it was reasonably working.


> what files are supposed to be edited(able)? only in http/ or also one level higher? if so, all files listed and therefore editable should be (pre)viewable then, that would be consistent logic.

If I remember correctly all .lua file are and should be editable, the "http" folder is there to clean a bit the mess of lua files (and to put them in logical location) even if lua does not really know what a folder is and in fact http/bla.lua is just the real name of the file, we could have use ":" or any other character as a "folder" delimiter here, it was just used the conventional "/".


> what does 'preview' actually mean here? the .lua file is compiled and executed in the context of httpserver.

That's part of the WebIDE that is slightly broken at the moment and a bit misleading. Some part of that IDE was hardcoded for certain behaviour, and the preview is one, that somethings I plan to change to make things more clear


> what about non-lua files? editable as well?

I don't remember, but I think it only list .lua files.
Ok just checked:
` if ((string.sub(n, -3) ~= '.gz') and (string.sub(n, -3) ~= '.lc')) then
               filelist[n] = s
            end`
It list all the files that are not ending with .lc (compiled LUA files) and .gz

So if you have an HTML file you should be able to edit it.


> make wifi.SOFTAP the default, change default password not be the SSID, but Pass<ID> as it was before.

I made the choice to not use SoftAP per default because some people will not change the default values and they are, honestly bad.
I do have plan to add a setting page to change the WiFi settings and other things, and then the first time it is started it will first start as a SoftAP and show a first time running page with choices of configurations.

> document basic functionality: what does the IDE actually do (lua vs non-lua files)? what's good practice to code with WebIDE and make it work beyond reboots.

And I completely agree with that, mine is poorly documented, but at least the code is not to badly organised, the original was poorly documented and, at least for me, a complete mess.

> ensure basic functionality working, the examples seem gone (unlisted), e.g. http/ws-echo.lua is listed, but http/ws-echo.html is not.

Hmmm I suspect that it is unlisted because the lua file was compiled into a .lc and the demo HTML files are, to save space, compressed as .gz file, so that's why they are not editable/visible


> introduce version numbering (itself and all parts)

I'm not sure what you call parts, but having WebIDE showing a version is a good idea

> keep track of components (not sure what's the best way, to have components improve yet to ensure they work properly = testing and documenting versions used)

Also not sure what you call components? but httpserver and uploader are both using git submodule 
and both are at a specific known version and will not change unless done by hand (git submodule update)

> provide .bin to start with for newbies, something to work out of the box (I'm willing to provide that)
Well as I said earlier, a .bin version that include nodemcu and the filesystem is I think a really bad idea.

The (non existing) documentation should explain how to install from scratch that a good idea, what can be done too is for each release build a .bin file that only contain the SPIFFS, so the filesystem, I saw a tool a couple of days ago that can be used for that, there are way to add that to the makefile.
As I was thinking into adding jenkins to do some check on the build of the IDE for each commit, I could easily add a way to generate that specific bin file for releases files (or should I say tagged commit)

But honestly a full .bin file that include both the interpreter and the filesystem will ask way more on the build process and the set of modules will be fine for some, but not to other, there is clearly no way to make all possible combination.
But if you want to that you are more than welcome, and I will happily add a link to your work!

And for your suggestions, you are welcome to open new "issues" for them, after all the issue tracker is also to tracker new functionalities and users wishes, not only bugs :)

Also if you or anyone want to work on some documentation, I can give you the rights on the Wiki to edit/update it (well would need to enable it before of course)

I hope I forgot nothing

Edit: well I've enabled the wiki, can't see any options to it, seems like anyone can edit it?!

**Comment by Spiritdude** [comment]
Regarding compressed .html, .lua etc of the examples:

The best way is **differentiate** between the **WebIDE** itself and the **rest of the files** which we should be able to edit/save/execute. 

I suggest httpserver serves any content (not just http/*) and we hide webide and httpserver code base via file-api.lua, so all other files become seen and editable. This makes it also easy to compress any component (.js, .html) of the WebIDE only and not mess with anything else (I lack the detail knowledge how and when .lua become .lc).

Possible layout:
- `ide/*` : all files of the WebIDE, .html, .lua, .js etc which can be compressed for upload, file-api.lua by default doesn't list those
  - `ide/http/*` all webgui parts
  - `ide/httpserver-*` all httpserver parts
- all other files remain untouched (e.g. examples/* contains the examples), setup.lua, startup.lua etc all properly 

@HHHartmann your thoughts?

**Comment by HHHartmann** [comment]
I think hiding the vital files is a good idea although I'd like to have an easy way to see/edit all files as a WebIDE developer. Maybe we can have a config section which files to hide.

Moving the httpserver to another location would require to change all httpserver internal calls to other parts of httpserver to the new path. This would generate a larger diff to apply which would likely break when updating to a new version of httpserver.

Also teaching httpserver to serve from different locations would result in a larger diff. Of course this could propably be merged into the upstream repo too,

For the time being we could probably put the WebIDE stuff in /http/ide/*

I would also like to have some easy way to upload/download files from/to the esp to get them in version control. Best in only one action, maybe packing/unpacking it from only one file on the esp.

Btw: I speak Lua but only limited html/js/css

**Comment by Spiritdude** [comment]
Btw, there is just one place where 'http/' is defined: `httpserver-request.lua`: `uriToFilename()`. I quickly changed it (`"http/"`.. -> `""..`) and I had to http://192.168.111.1/http/index.html and change one line in `index.js`: `execute()` (formerly `preview()`), and the WebIDE seems to work (still just a few examples).

I also combined "select" & "execute" (formerly "preview"), you select a file it loads into the editor and executes it and output in new output DIV; it's quite handy and saves a step - but one has to be careful to execute init.lua or startup.lua (it crashes httpserver). 

I will play a bit further with my setup before I make a PR.

**Comment by Godzil** [comment]
Well I will be direct on that, changing the serving path of httpserver is a potential security issue, especially if set to the root. Keeping the served pages in a folder allow to keep scripts in a place that can’t be accessed by a browser. (Script as root and other root folder than /http/.

If not, someone could be able to run the unit/startup script for example by just calling it in the URL (http://ip/init.lua) and it can led to some unwanted behaviour,

and as I’m trying to reduce the alount if patch and not increase it, that’s not great, and I doubt that hat this would be accepted as a change for httpserve as they moved to a folder for cleanup reason and potential security issues.

You are welcome for you other changes, would be happy to see how it improve the currently « broken » workflow. Please keep in mind that I want to update the base IDE which will probably bring some new functionality like multiples opened tabs in the IDE.

Could we continue this discussions in a another issues as it is unrelated with uploaded? Thanks :)

**Comment by Spiritdude** [comment]
I opened an issue of the main bugs we discussed. And another issue of the output concept (no new tabs but inline).
